### ISSUE TITLE
Add new branch hit error in SQL statement

### ISSUE THREAD

**Issue by alexissinglaire** [myckhel/church-management-system#30]
Adding new branch  (admin tools | add new branch) encountered error. I noticed the SQL statement for MYSQL is incorrect. The value of the columns should have apostrophe in between. You dont need to use apostrophe in between for the column name or table name, just the column value will do. 

the incorrect SQL statement:
insert into `users` (`branchname`, `branchcode`, `address`, `email`, `isadmin`, `password`, `country`, `state`, `city`, `currency`, `updated_at`, `created_at`) values (SBC3, SBC3, SURABAYA RAYA, alexisdemo009@gmail.com, 0, $2y$10$1.GTKsJjPybLOGZXozuFW.G/.Cb0u1npq3DZFzL.3zQQtY.C5q/Ri, Indonesia, JAWA TIMUR, SURABAYA, Rp, 2021-04-27 03:13:07, 2021-04-27 03:13:07)

the correct SQL statement:
insert into users (branchname, branchcode, address, email, isadmin, password, country, state, city, currency, updated_at, created_at) values ('SBC3', 'SBC3', 'SURABAYA RAYA', 'alexisdemo009@gmail.com', 0, '$2y$10$1.GTKsJjPybLOGZXozuFW.G/.Cb0u1npq3DZFzL.3zQQtY.C5q/Ri', 'Indonesia', 'JAWA TIMUR', 'SURABAYA', 'Rp', '2021-04-27 03:13:07', '2021-04-27 03:13:07')

For the varchar  column, you should put apostrophe in between for the column value. 

![image](https://user-images.githubusercontent.com/17283778/116180050-e36e3080-a74a-11eb-9290-55125e3d1f4f.png)

**Comment by myckhel** [comment]
fixed https://github.com/myckhel/church-management-system/commit/0eeb1907f5788a74fb3a5c91e6f6b075cdfee74e
