### ISSUE TITLE
Error during package installation

### ISSUE THREAD

**Issue by theophilusjtt** [myckhel/church-management-system#35]
![error](https://user-images.githubusercontent.com/24839823/125436516-1cebb2f3-45ee-42b6-9d73-cc2ce616c0cf.PNG)
am facing this challenge while installing the package. please assist me.

**Comment by theophilusjtt** [comment]
ok

**Comment by theophilusjtt** [comment]
I think i have to use a lower version of PHP

**Comment by myckhel** [comment]
php 7 supported for now until i update

**Comment by theophilusjtt** [comment]
This is the feedback after manual update 

Microsoft Windows [Version 10.0.21996.1]
(c) Microsoft Corporation. All rights reserved.

C:\Users\AFRITECHS GH>cd C:\xampp\htdocs\church-management-system-master

C:\xampp\htdocs\church-management-system-master>composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires php ^7.1.3 but your php version (8.0.7) does not satisfy that requirement.
  Problem 2
    - doctrine/inflector is locked to version v1.3.0 and an update of this package was not requested.
    - doctrine/inflector v1.3.0 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 3
    - laravel/framework is locked to version v5.7.27 and an update of this package was not requested.
    - laravel/framework v5.7.27 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 4
    - laravel/nexmo-notification-channel is locked to version v1.0.1 and an update of this package was not requested.
    - laravel/nexmo-notification-channel v1.0.1 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 5
    - laravel/slack-notification-channel is locked to version v1.0.3 and an update of this package was not requested.
    - laravel/slack-notification-channel v1.0.3 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 6
    - opis/closure is locked to version 3.1.5 and an update of this package was not requested.
    - opis/closure 3.1.5 requires php ^5.4 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 7
    - paragonie/random_compat is locked to version v9.99.99 and an update of this package was not requested.
    - paragonie/random_compat v9.99.99 requires php ^7 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 8
    - ramsey/uuid is locked to version 3.8.0 and an update of this package was not requested.
    - ramsey/uuid 3.8.0 requires php ^5.4 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 9
    - symfony/console is locked to version v4.2.3 and an update of this package was not requested.
    - symfony/console v4.2.3 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 10
    - symfony/contracts is locked to version v1.0.2 and an update of this package was not requested.
    - symfony/contracts v1.0.2 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 11
    - symfony/css-selector is locked to version v4.2.3 and an update of this package was not requested.
    - symfony/css-selector v4.2.3 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 12
    - symfony/debug is locked to version v4.2.3 and an update of this package was not requested.
    - symfony/debug v4.2.3 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 13
    - symfony/event-dispatcher is locked to version v4.2.3 and an update of this package was not requested.
    - symfony/event-dispatcher v4.2.3 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 14
    - symfony/finder is locked to version v4.2.3 and an update of this package was not requested.
    - symfony/finder v4.2.3 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 15
    - symfony/http-foundation is locked to version v4.4.1 and an update of this package was not requested.
    - symfony/http-foundation v4.4.1 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 16
    - symfony/http-kernel is locked to version v4.2.3 and an update of this package was not requested.
    - symfony/http-kernel v4.2.3 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 17
    - symfony/mime is locked to version v4.4.1 and an update of this package was not requested.
    - symfony/mime v4.4.1 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 18
    - symfony/process is locked to version v4.2.3 and an update of this package was not requested.
    - symfony/process v4.2.3 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 19
    - symfony/routing is locked to version v4.2.3 and an update of this package was not requested.
    - symfony/routing v4.2.3 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 20
    - symfony/translation is locked to version v4.2.3 and an update of this package was not requested.
    - symfony/translation v4.2.3 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 21
    - symfony/var-dumper is locked to version v4.2.3 and an update of this package was not requested.
    - symfony/var-dumper v4.2.3 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 22
    - tijsverkoyen/css-to-inline-styles is locked to version 2.2.1 and an update of this package was not requested.
    - tijsverkoyen/css-to-inline-styles 2.2.1 requires php ^5.5 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 23
    - unicodeveloper/laravel-paystack is locked to version 1.0.2 and an update of this package was not requested.
    - unicodeveloper/laravel-paystack 1.0.2 requires php ^5.4.0|^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 24
    - zendframework/zend-diactoros is locked to version 1.8.6 and an update of this package was not requested.
    - zendframework/zend-diactoros 1.8.6 requires php ^5.6 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 25
    - beyondcode/laravel-dump-server is locked to version 1.2.2 and an update of this package was not requested.
    - beyondcode/laravel-dump-server 1.2.2 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 26
    - doctrine/instantiator is locked to version 1.1.0 and an update of this package was not requested.
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 27
    - filp/whoops is locked to version 2.3.1 and an update of this package was not requested.
    - filp/whoops 2.3.1 requires php ^5.5.9 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 28
    - fzaninotto/faker is locked to version v1.8.0 and an update of this package was not requested.
    - fzaninotto/faker v1.8.0 requires php ^5.3.3 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 29
    - hamcrest/hamcrest-php is locked to version v2.0.0 and an update of this package was not requested.
    - hamcrest/hamcrest-php v2.0.0 requires php ^5.3|^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 30
    - myclabs/deep-copy is locked to version 1.8.1 and an update of this package was not requested.
    - myclabs/deep-copy 1.8.1 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 31
    - nunomaduro/collision is locked to version v2.1.1 and an update of this package was not requested.
    - nunomaduro/collision v2.1.1 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 32
    - phar-io/manifest is locked to version 1.0.3 and an update of this package was not requested.
    - phar-io/manifest 1.0.3 requires php ^5.6 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 33
    - phar-io/version is locked to version 2.0.1 and an update of this package was not requested.
    - phar-io/version 2.0.1 requires php ^5.6 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 34
    - phpdocumentor/reflection-docblock is locked to version 4.3.0 and an update of this package was not requested.
    - phpdocumentor/reflection-docblock 4.3.0 requires php ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 35
    - phpdocumentor/type-resolver is locked to version 0.4.0 and an update of this package was not requested.
    - phpdocumentor/type-resolver 0.4.0 requires php ^5.5 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 36
    - phpspec/prophecy is locked to version 1.8.0 and an update of this package was not requested.
    - phpspec/prophecy 1.8.0 requires php ^5.3|^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 37
    - phpunit/php-code-coverage is locked to version 6.1.4 and an update of this package was not requested.
    - phpunit/php-code-coverage 6.1.4 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 38
    - phpunit/php-file-iterator is locked to version 2.0.2 and an update of this package was not requested.
    - phpunit/php-file-iterator 2.0.2 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 39
    - phpunit/php-timer is locked to version 2.1.1 and an update of this package was not requested.
    - phpunit/php-timer 2.1.1 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 40
    - phpunit/php-token-stream is locked to version 3.0.1 and an update of this package was not requested.
    - phpunit/php-token-stream 3.0.1 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 41
    - phpunit/phpunit is locked to version 7.5.6 and an update of this package was not requested.
    - phpunit/phpunit 7.5.6 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 42
    - sebastian/code-unit-reverse-lookup is locked to version 1.0.1 and an update of this package was not requested.
    - sebastian/code-unit-reverse-lookup 1.0.1 requires php ^5.6 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 43
    - sebastian/comparator is locked to version 3.0.2 and an update of this package was not requested.
    - sebastian/comparator 3.0.2 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 44
    - sebastian/diff is locked to version 3.0.2 and an update of this package was not requested.
    - sebastian/diff 3.0.2 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 45
    - sebastian/environment is locked to version 4.1.0 and an update of this package was not requested.
    - sebastian/environment 4.1.0 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 46
    - sebastian/exporter is locked to version 3.1.0 and an update of this package was not requested.
    - sebastian/exporter 3.1.0 requires php ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 47
    - sebastian/global-state is locked to version 2.0.0 and an update of this package was not requested.
    - sebastian/global-state 2.0.0 requires php ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 48
    - sebastian/object-enumerator is locked to version 3.0.3 and an update of this package was not requested.
    - sebastian/object-enumerator 3.0.3 requires php ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 49
    - sebastian/object-reflector is locked to version 1.1.1 and an update of this package was not requested.
    - sebastian/object-reflector 1.1.1 requires php ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 50
    - sebastian/recursion-context is locked to version 3.0.0 and an update of this package was not requested.
    - sebastian/recursion-context 3.0.0 requires php ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 51
    - sebastian/resource-operations is locked to version 2.0.1 and an update of this package was not requested.
    - sebastian/resource-operations 2.0.1 requires php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 52
    - theseer/tokenizer is locked to version 1.1.0 and an update of this package was not requested.
    - theseer/tokenizer 1.1.0 requires php ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 53
    - webmozart/assert is locked to version 1.4.0 and an update of this package was not requested.
    - webmozart/assert 1.4.0 requires php ^5.3.3 || ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
  Problem 54
    - laravel/framework v5.7.27 requires php ^7.1.3 -> your php version (8.0.7) does not satisfy that requirement.
    - yajra/laravel-datatables-oracle v8.13.5 requires illuminate/database 5.4.*|5.5.*|5.6.*|5.7.* -> satisfiable by laravel/framework[v5.7.27].
    - yajra/laravel-datatables-oracle is locked to version v8.13.5 and an update of this package was not requested.


C:\xampp\htdocs\church-management-system-master>

**Comment by myckhel** [comment]
issue solved?

**Comment by theophilusjtt** [comment]
no, please

**Comment by myckhel** [comment]
you have 3 options
- wait until i make update
- downgrade php to v7
- upgrade dependencies, add php 8 support and fix issues during upgrade

**Comment by theophilusjtt** [comment]
I have already downgraded to version 7, before the dependencies downloaded

**Comment by theophilusjtt** [comment]
![Capture 5](https://user-images.githubusercontent.com/24839823/125525382-7ffaebce-83a0-45ba-9b6e-78d250a86654.JPG)

**Comment by myckhel** [comment]
Have you?

temporary update         `unicodeveloper/laravel-paystack` to `1.0.7`
from this line https://github.com/myckhel/church-management-system/blob/0eeb1907f5788a74fb3a5c91e6f6b075cdfee74e/composer.json#L18
before downloading dependencies.

**Comment by theophilusjtt** [comment]
ok

**Comment by theophilusjtt** [comment]
it is still the same error
