### ISSUE TITLE
error

### ISSUE THREAD

**Issue by theophilusjtt** [myckhel/church-management-system#39]
![Capture error](https://user-images.githubusercontent.com/24839823/127987044-77962041-a735-4de1-819a-188019a25d3c.JPG)

Please I will like to know the XAMPP module or version is compatible with this installaion.

Thank you.

**Comment by theophilusjtt** [comment]
Kindly go through and suggest to me what I should do. 

Thank you.


C:\Users\AFRITECHS GH>cd C:\xampp\htdocs\church-management-system-master

C:\xampp\htdocs\church-management-system-master>composer upgrade
Loading composer repositories with package information
Updating dependencies
Lock file operations: 4 installs, 26 updates, 0 removals
  - Locking dflydev/dot-access-data (v3.0.0)
  - Upgrading facade/ignition (2.11.0 => 2.11.2)
  - Upgrading laravel/framework (v8.50.0 => v8.52.0)
  - Upgrading league/commonmark (1.6.5 => 2.0.1)
  - Locking league/config (v1.1.0)
  - Upgrading monolog/monolog (2.3.0 => 2.3.2)
  - Upgrading nesbot/carbon (2.50.0 => 2.51.1)
  - Locking nette/schema (v1.2.1)
  - Locking nette/utils (v3.2.2)
  - Upgrading nikic/php-parser (v4.11.0 => v4.12.0)
  - Upgrading nunomaduro/collision (v5.5.0 => v5.6.0)
  - Upgrading phar-io/manifest (2.0.1 => 2.0.3)
  - Upgrading phpunit/phpunit (9.5.6 => 9.5.8)
  - Upgrading ramsey/collection (1.1.3 => 1.1.4)
  - Upgrading symfony/console (v5.3.2 => v5.3.6)
  - Upgrading symfony/css-selector (v5.3.0 => v5.3.4)
  - Upgrading symfony/error-handler (v5.3.3 => v5.3.4)
  - Upgrading symfony/event-dispatcher (v5.3.0 => v5.3.4)
  - Upgrading symfony/finder (v5.3.0 => v5.3.4)
  - Upgrading symfony/http-foundation (v5.3.3 => v5.3.6)
  - Upgrading symfony/http-kernel (v5.3.3 => v5.3.6)
  - Upgrading symfony/mime (v5.3.2 => v5.3.4)
  - Upgrading symfony/polyfill-intl-grapheme (v1.23.0 => v1.23.1)
  - Upgrading symfony/polyfill-mbstring (v1.23.0 => v1.23.1)
  - Upgrading symfony/polyfill-php80 (v1.23.0 => v1.23.1)
  - Upgrading symfony/process (v5.3.2 => v5.3.4)
  - Upgrading symfony/routing (v5.3.0 => v5.3.4)
  - Upgrading symfony/translation (v5.3.3 => v5.3.4)
  - Upgrading symfony/var-dumper (v5.3.3 => v5.3.6)
  - Upgrading theseer/tokenizer (1.2.0 => 1.2.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 42 installs, 19 updates, 0 removals
  - Downloading symfony/polyfill-php80 (v1.23.1)
  - Downloading symfony/polyfill-mbstring (v1.23.1)
  - Downloading symfony/var-dumper (v5.3.6)
  - Downloading symfony/css-selector (v5.3.4)
  - Downloading symfony/routing (v5.3.4)
  - Downloading symfony/process (v5.3.4)
  - Downloading symfony/mime (v5.3.4)
  - Downloading symfony/http-foundation (v5.3.6)
  - Downloading symfony/event-dispatcher (v5.3.4)
  - Downloading symfony/error-handler (v5.3.4)
  - Downloading symfony/http-kernel (v5.3.6)
  - Downloading symfony/finder (v5.3.4)
  - Downloading symfony/polyfill-intl-grapheme (v1.23.1)
  - Downloading symfony/console (v5.3.6)
  - Downloading ramsey/collection (1.1.4)
  - Downloading symfony/translation (v5.3.4)
  - Downloading nesbot/carbon (2.51.1)
  - Downloading monolog/monolog (2.3.2)
  - Downloading nette/utils (v3.2.2)
  - Downloading nette/schema (v1.2.1)
  - Downloading dflydev/dot-access-data (v3.0.0)
  - Downloading league/config (v1.1.0)
  - Downloading league/commonmark (2.0.1)
  - Downloading laravel/framework (v8.52.0)
  - Downloading facade/ignition (2.11.2)
  - Downloading nikic/php-parser (v4.12.0)
  - Downloading nunomaduro/collision (v5.6.0)
  - Downloading theseer/tokenizer (1.2.1)
  - Downloading phar-io/manifest (2.0.3)
  - Downloading phpunit/phpunit (9.5.8)
  - Installing symfony/polyfill-php80 (v1.23.1): Extracting archive
  - Upgrading symfony/polyfill-mbstring (v1.23.0 => v1.23.1): Extracting archive
  - Upgrading symfony/var-dumper (v5.3.3 => v5.3.6): Extracting archive
  - Installing voku/portable-ascii (1.5.6): Extracting archive
  - Installing phpoption/phpoption (1.7.5): Extracting archive
  - Installing graham-campbell/result-type (v1.0.1): Extracting archive
  - Upgrading symfony/css-selector (v5.3.0 => v5.3.4): Extracting archive
  - Installing symfony/deprecation-contracts (v2.4.0): Extracting archive
  - Upgrading symfony/routing (v5.3.0 => v5.3.4): Extracting archive
  - Upgrading symfony/process (v5.3.2 => v5.3.4): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.23.0): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.23.0): Extracting archive
  - Installing symfony/mime (v5.3.4): Extracting archive
  - Installing symfony/polyfill-php73 (v1.23.0): Extracting archive
  - Upgrading symfony/http-foundation (v5.3.3 => v5.3.6): Extracting archive
  - Installing symfony/http-client-contracts (v2.4.0): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v2.4.0): Extracting archive
  - Upgrading symfony/event-dispatcher (v5.3.0 => v5.3.4): Extracting archive
  - Installing symfony/error-handler (v5.3.4): Extracting archive
  - Upgrading symfony/http-kernel (v5.3.3 => v5.3.6): Extracting archive
  - Upgrading symfony/finder (v5.3.0 => v5.3.4): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.23.1): Extracting archive
  - Installing symfony/string (v5.3.3): Extracting archive
  - Installing symfony/service-contracts (v2.4.0): Extracting archive
  - Upgrading symfony/console (v5.3.2 => v5.3.6): Extracting archive
  - Installing symfony/polyfill-iconv (v1.23.0): Extracting archive
  - Installing ramsey/collection (1.1.4): Extracting archive
  - Installing brick/math (0.9.2): Extracting archive
  - Installing symfony/translation-contracts (v2.4.0): Extracting archive
  - Upgrading symfony/translation (v5.3.3 => v5.3.4): Extracting archive
  - Upgrading nesbot/carbon (2.50.0 => 2.51.1): Extracting archive
  - Upgrading monolog/monolog (2.3.0 => 2.3.2): Extracting archive
  - Installing league/mime-type-detection (1.7.0): Extracting archive
  - Installing nette/utils (v3.2.2): Extracting archive
  - Installing nette/schema (v1.2.1): Extracting archive
  - Installing dflydev/dot-access-data (v3.0.0): Extracting archive
  - Installing league/config (v1.1.0): Extracting archive
  - Installing league/commonmark (2.0.1): Extracting archive
  - Upgrading laravel/framework (v8.50.0 => v8.52.0): Extracting archive
  - Installing dcblogdev/laravel-countries (v2.0.0): Extracting archive
  - Installing facade/ignition-contracts (1.0.2): Extracting archive
  - Installing facade/flare-client-php (1.8.1): Extracting archive
  - Installing facade/ignition (2.11.2): Extracting archive
  - Installing fakerphp/faker (v1.15.0): Extracting archive
  - Installing asm89/stack-cors (v2.0.3): Extracting archive
  - Installing fruitcake/laravel-cors (v2.0.4): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Upgrading nikic/php-parser (v4.11.0 => v4.12.0): Extracting archive
  - Installing laravel/ui (v3.3.0): Extracting archive
  - Upgrading nunomaduro/collision (v5.5.0 => v5.6.0): Extracting archive
  - Installing sebastian/type (2.3.4): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Upgrading theseer/tokenizer (1.2.0 => 1.2.1): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Upgrading phar-io/manifest (2.0.1 => 2.0.3): Extracting archive
  - Upgrading phpunit/phpunit (9.5.6 => 9.5.8): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
2 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating optimized autoload files
Class Unicodeveloper\Paystack\Exceptions\IsNullException located in C:/xampp/htdocs/church-management-system-master/vendor/unicodeveloper/laravel-paystack/src\Exceptions\isNullException.php does not comply with psr-4 autoloading standard. Skipping.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Script Illuminate\Foundation\ComposerScripts::postAutoloadDump handling the post-autoload-dump event terminated with an exception


  [ErrorException]
  require(C:\xampp\htdocs\church-management-system-master\vendor\composer/../ramsey/uuid/src/functions.php): Failed t
  o open stream: No such file or directory


update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...


C:\xampp\htdocs\church-management-system-master>composer suggest
facade/ignition suggests:
 - laravel/telescope: ^3.1

guzzlehttp/guzzle suggests:
 - ext-intl: Required for Internationalized Domain Name (IDN) support

laravel/framework suggests:
 - aws/aws-sdk-php: Required to use the SQS queue driver, DynamoDb failed job storage and SES mail driver (^3.155).
 - brianium/paratest: Required to run tests in parallel (^6.0).
 - doctrine/dbal: Required to rename columns and drop SQLite columns (^2.6|^3.0).
 - ext-gd: Required to use Illuminate\Http\Testing\FileFactory::image().
 - ext-memcached: Required to use the memcache cache driver.
 - ext-pcntl: Required to use all features of the queue worker.
 - ext-posix: Required to use all features of the queue worker.
 - ext-redis: Required to use the Redis cache and queue drivers (^4.0|^5.0).
 - league/flysystem-aws-s3-v3: Required to use the Flysystem S3 driver (^1.0).
 - league/flysystem-cached-adapter: Required to use the Flysystem cache (^1.0).
 - league/flysystem-sftp: Required to use the Flysystem SFTP driver (^1.0).
 - nyholm/psr7: Required to use PSR-7 bridging features (^1.2).
 - pda/pheanstalk: Required to use the beanstalk queue driver (^4.0).
 - predis/predis: Required to use the predis connector (^1.1.2).
 - pusher/pusher-php-server: Required to use the Pusher broadcast driver (^4.0|^5.0|^6.0).
 - symfony/cache: Required to PSR-6 cache bridge (^5.1.4).
 - symfony/filesystem: Required to enable support for relative symbolic links (^5.1.4).
 - symfony/psr-http-message-bridge: Required to use PSR-7 bridging features (^2.0).
 - wildbit/swiftmailer-postmark: Required to use Postmark mail driver (^3.0).

phpunit/phpunit suggests:
 - ext-soap: *
 - ext-xdebug: *

yajra/laravel-datatables-oracle suggests:
 - yajra/laravel-datatables-buttons: Plugin for server-side exporting of dataTables.
 - yajra/laravel-datatables-editor: Plugin to use DataTables Editor (requires a license).
 - yajra/laravel-datatables-fractal: Plugin for server-side response using Fractal.
 - yajra/laravel-datatables-html: Plugin for server-side HTML builder of dataTables.

59 additional suggestions by transitive dependencies can be shown with --all

**Comment by myckhel** [comment]
Just try to clone master branch to get latest update.
I guess you are using an outdated master branch.

**Comment by theophilusjtt** [comment]
Please can I give you access to Anydesk to try it for me?

**Comment by theophilusjtt** [comment]
Please can I get your WhatsApp number for easy communication?

**Comment by theophilusjtt** [comment]
> Just try to clone master branch to get latest update.
> I guess you are using an outdated master branch.

Please how do I clone it?

**Comment by myckhel** [comment]
Goto my github profile 
Click the website
You will see my WhatsApp button

**Comment by theophilusjtt** [comment]
> Please can I get your WhatsApp number for easy communication?

My is +233276202090 or +233546324861

**Comment by theophilusjtt** [comment]
ok

> Goto my github profile
> Click the website
> You will see my WhatsApp button

ok
