### ISSUE TITLE
blank page after installation

### ISSUE THREAD

**Issue by lampatt** [myckhel/church-management-system#4]
l get a blank page after successfully done the installation. Please advise

**Comment by myckhel** [comment]
you may checkout the development branch and migrate the db.
its possible you encounter issues because its still currently under development.

**Comment by lampatt** [comment]
Ok thanks will get back to you on that please. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by myckhel** [comment]
Note
To set up

Follow this step

Clone the project
Cd into the project
Composer install from cmd
Copy .env.example to .env
Change the settings in the created .env file
Php artisan key:generate. From cmd
Create database table
Php artisan migrate


Then the app is ready with some bugs

You may fix some buy making a pull request.

Thanks

**Comment by Prale** [comment]
I have managed to import project into my localhost, but on registering new account its stuck on name and logo upload. Localhost keep giving pop up which says "undefined" please help

**Comment by myckhel** [comment]
please make sure u are using the development branch if not switch to the development branch, the branch is updated.

**Comment by lampatt** [comment]
Thank you very much. I will work on that exactly as directed. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
