### ISSUE TITLE
Demo Account

### ISSUE THREAD

**Issue by raphawa** [myckhel/church-management-system#45]
Hello and thanks for hard work you doing on this project.
Can I have a demo account to test  admin?
Also need how does the attendance work. Does it work with a barcode scanner or qr code?

**Comment by myckhel** [comment]
Url: https://cms.myckhel.com/login
Email: kylemoose45@gmail.com
Password: 123456789

> Also need how does the attendance work. Does it work with a barcode scanner or qr code?

Does not work with any of them.
