### ISSUE TITLE
Issue with index.php while deploying

### ISSUE THREAD

**Issue by paulwababu** [myckhel/church-management-system#54]
i get an error while deploying the app using apache, 
for /dashboard route, i need to add /index.php/dashboard for it to work, this is a problem as all the static files cannot load, please share your apache configs if possible

**Comment by myckhel** [comment]
Point your document root to /public 📂. That should work

**Comment by paulwababu** [comment]
THank you, alternatively, you could 
sudo a2enmod rewrite
