### ISSUE TITLE
Image Upload Not Working

### ISSUE THREAD

**Issue by paulkiragu621** [myckhel/church-management-system#57]
Tried Uploading image of member registration, it shows successful, but i cannot see the image of the user that i have just uploaded

**Comment by myckhel** [comment]
Yes it doesnt work.
I will try to debug and fix the issue when have the time and will ref the commit in this issue.

**Comment by myckhel** [comment]
Lets leave it opened until its fixed.

**Comment by myckhel** [comment]
Fixed In: https://github.com/myckhel/church-management-system/commit/f0dc21a961b01f597c2eedade2d762d111570015
