### ISSUE TITLE
Undefined variable convertedDate

### ISSUE THREAD

**Issue by Ansah7** [myckhel/church-management-system#73]
When a date is selected to view attendance. Internal server error appears

![image](https://user-images.githubusercontent.com/23300221/235378942-ed10bbf1-10b7-4a25-9b23-34d9d84b50f4.png)

**Comment by Ansah7** [comment]
I resolved by placing $convertedDate with $request->get('date') in get_date_in_words function in line 109.
return response()->json(['status' => false, 'text' => "No attendance data for {$this->get_date_in_words(**$request->get('date')**)}"]);
![image](https://user-images.githubusercontent.com/23300221/235380529-45481b36-d0a1-41dd-a73f-020c0820d440.png)

**Comment by myckhel** [comment]
Would be nice if you can make a pull request for your fix
