### ISSUE TITLE
Fields not matching when editing registered members

### ISSUE THREAD

**Issue by Ansah7** [myckhel/church-management-system#76]
## Creation
![image](https://user-images.githubusercontent.com/23300221/235432430-6c99a4d9-db65-43fa-9b3a-b8dd499e57a3.png)

## Editing, Details highlighted below.
![image](https://user-images.githubusercontent.com/23300221/235432585-4b29a1c6-48f4-4b2e-ae68-d3726ad1a61a.png)

**Comment by myckhel** [comment]
Will check it out.

i will assign myself as soon as i started the fix

**Comment by nathan141-spec** [comment]
Hello, i change the i == ... only to i == 9 and match it with the column, after i restart it, it work
![SS-1](https://github.com/myckhel/church-management-system/assets/80805592/5d6f9fe5-cbd0-45da-9aa3-1e7d3dddb4a5)
![SS-2](https://github.com/myckhel/church-management-system/assets/80805592/96da1ca9-11e4-4ca1-a815-7762334c19f1)

**Comment by Ansah7** [comment]
Hi Nathan,
Thanks. Can you raise a PR?

**Comment by nathan141-spec** [comment]
im sorry, can you enlight how to raise a PR ? because im not to familiar with Github

**Comment by myckhel** [comment]
- commit the changes to your branch
- push the changes to your repository
- goto your repository and click pull request
- open pull request to this repository
- i will look into your changes and may merge the changes into this repo

**Comment by Ansah7** [comment]
Hi @nathan141-spec
Please follow this. Once it's reviewed by @myckhel author he will approve it. 
https://opensource.com/article/19/7/create-pull-request-github

**Comment by Ansah7** [comment]
Hi @nathan141-spec ,
Were you able to figure out how to do the pull request?
